ALTER TABLE metastore.table_params CHANGE COLUMN PARAM_VALUE PARAM_VALUE VARCHAR(4000) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL COMMENT '';
ALTER TABLE metastore.columns_v2 CHANGE COLUMN COMMENT COMMENT VARCHAR(256) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL COMMENT '';
