USE default;

CREATE TABLE IF NOT EXISTS userinfo ( uname STRING, pswd STRING, uid INT, gid INT, fullname STRING, hdir STRING, shell STRING ) ROW FORMAT DELIMITED FIELDS TERMINATED BY ':' STORED AS TEXTFILE;
LOAD DATA INPATH '${input}' OVERWRITE INTO TABLE userinfo;